import { db } from "@workspace/db";
import { venuesTable } from "@workspace/db/schema";
import { count } from "drizzle-orm";
import { logger } from "./logger";

const VENUES = [
  {
    name: "Sightglass Coffee",
    neighborhood: "SoMa",
    address: "270 7th St, San Francisco, CA 94103",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "laptop-friendly", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 5,
    hours: "Mon–Fri 7am–5pm, Sat–Sun 8am–5pm",
    mapsUrl: "https://maps.google.com/?q=Sightglass+Coffee+270+7th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Stunning industrial space with incredible pour-overs.",
  },
  {
    name: "Ritual Coffee Roasters",
    neighborhood: "Mission",
    address: "1026 Valencia St, San Francisco, CA 94110",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Daily 7am–6pm",
    mapsUrl: "https://maps.google.com/?q=Ritual+Coffee+Roasters+Valencia+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "SF specialty pioneer. Excellent single-origins.",
  },
  {
    name: "Saint Frank Coffee",
    neighborhood: "Russian Hill",
    address: "2340 Polk St, San Francisco, CA 94109",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi", "outlets", "laptop-friendly", "quiet"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Saint+Frank+Coffee+Polk+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Refined neighborhood roaster. Great for focused work.",
  },
  {
    name: "Verve Coffee Roasters",
    neighborhood: "SoMa",
    address: "580 Howard St, San Francisco, CA 94105",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi", "outlets", "founder-crowd"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Mon–Fri 6:30am–5pm, Sat–Sun 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Verve+Coffee+Roasters+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Santa Cruz roaster with a beautiful SoMa outpost.",
  },
  {
    name: "Andytown Coffee Roasters",
    neighborhood: "Outer Sunset",
    address: "3655 Lawton St, San Francisco, CA 94122",
    category: "coffee-only" as const,
    tags: JSON.stringify(["interesting-beans", "neighborhood", "cozy"]),
    workRating: 3,
    coffeeRating: 5,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Andytown+Coffee+Lawton+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "The Sunset's beloved roaster. Try the snowy plover.",
  },
  {
    name: "Flywheel Coffee Roasters",
    neighborhood: "Haight",
    address: "672 Stanyan St, San Francisco, CA 94117",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "neighborhood", "quiet", "cozy"]),
    workRating: 3,
    coffeeRating: 4,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Flywheel+Coffee+Stanyan+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Haight mainstay with serious sourcing ethics.",
  },
  {
    name: "Wrecking Ball Coffee Roasters",
    neighborhood: "Pacific Heights",
    address: "2271 Union St, San Francisco, CA 94123",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Wrecking+Ball+Coffee+Union+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "World-class roaster on a prime Cow Hollow block.",
  },
  {
    name: "Equator Coffees",
    neighborhood: "Multiple",
    address: "986 Market St, San Francisco, CA 94102",
    category: "coffee-only" as const,
    tags: JSON.stringify(["interesting-beans", "wifi", "outlets"]),
    workRating: 4,
    coffeeRating: 4,
    hours: "Mon–Fri 6am–6pm, Sat–Sun 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Equator+Coffees+Market+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "B-corp certified, excellent espresso program.",
  },
  {
    name: "Snowbird Coffee",
    neighborhood: "Russian Hill",
    address: "1352 Polk St, San Francisco, CA 94109",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "neighborhood", "quiet"]),
    workRating: 3,
    coffeeRating: 4,
    hours: "Daily 7am–4pm",
    mapsUrl: "https://maps.google.com/?q=Snowbird+Coffee+Polk+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Tiny, perfect Polk Street gem.",
  },
  {
    name: "The Coffee Movement",
    neighborhood: "SoMa",
    address: "66 Mint St, San Francisco, CA 94103",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi", "outlets", "laptop-friendly", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 4,
    hours: "Mon–Fri 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=The+Coffee+Movement+Mint+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Hidden SoMa gem, rotating guest roasters.",
  },
  {
    name: "Sextant Coffee Roasters",
    neighborhood: "SoMa",
    address: "1415 Folsom St, San Francisco, CA 94103",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "laptop-friendly", "founder-crowd"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Mon–Fri 7am–5pm, Sat 8am–4pm",
    mapsUrl: "https://maps.google.com/?q=Sextant+Coffee+Folsom+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Ethiopian-owned roaster with incredible naturals.",
  },
  {
    name: "Home Coffee Roasters",
    neighborhood: "Outer Richmond",
    address: "685 14th Ave, San Francisco, CA 94118",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "neighborhood", "cozy", "quiet"]),
    workRating: 3,
    coffeeRating: 4,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Home+Coffee+Roasters+14th+Ave+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Intimate Richmond district roaster with a home-away-from-home feel.",
  },
  {
    name: "Réveille Coffee — Jackson Square",
    neighborhood: "Financial District",
    address: "200 Pacific Ave, San Francisco, CA 94111",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi", "outlets", "laptop-friendly", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 5,
    hours: "Mon–Fri 6:30am–4pm",
    mapsUrl: "https://maps.google.com/?q=Reveille+Coffee+Pacific+Ave+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Best work café in FiDi. Quiet, fast wifi, stellar coffee.",
  },
  {
    name: "Linea Caffe",
    neighborhood: "Mission",
    address: "3417 18th St, San Francisco, CA 94110",
    category: "coffee-only" as const,
    tags: JSON.stringify(["espresso", "interesting-beans", "neighborhood"]),
    workRating: 2,
    coffeeRating: 5,
    hours: "Mon–Sat 7am–4pm, Sun 8am–3pm",
    mapsUrl: "https://maps.google.com/?q=Linea+Caffe+18th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Tiny espresso bar. No laptops, but transcendent shots.",
  },
  {
    name: "Paramo Coffee",
    neighborhood: "Multiple",
    address: "3600 20th St, San Francisco, CA 94110",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "wifi"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Mon–Fri 7am–5pm, Sat–Sun 8am–5pm",
    mapsUrl: "https://maps.google.com/?q=Paramo+Coffee+20th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Standout specialty with Colombian roots.",
  },
  {
    name: "The Grove",
    neighborhood: "Pacific Heights",
    address: "2250 Chestnut St, San Francisco, CA 94123",
    category: "coffee-food" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "food-available"]),
    workRating: 4,
    coffeeRating: 3,
    hours: "Daily 7am–9pm",
    mapsUrl: "https://maps.google.com/?q=The+Grove+Chestnut+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Cozy neighborhood café with all-day food and long open hours.",
  },
  {
    name: "Coffee Bar",
    neighborhood: "SoMa",
    address: "1890 Bryant St, San Francisco, CA 94110",
    category: "coffee-food" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "food-available", "roomy", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 4,
    hours: "Mon–Fri 7am–6pm, Sat 8am–5pm",
    mapsUrl: "https://maps.google.com/?q=Coffee+Bar+Bryant+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Sprawling SoMa warehouse space, excellent for all-day work sessions.",
  },
  {
    name: "Tartine Manufactory",
    neighborhood: "Mission",
    address: "595 Alabama St, San Francisco, CA 94110",
    category: "coffee-food" as const,
    tags: JSON.stringify(["interesting-beans", "food-available", "neighborhood"]),
    workRating: 2,
    coffeeRating: 4,
    hours: "Daily 8am–5pm",
    mapsUrl: "https://maps.google.com/?q=Tartine+Manufactory+Alabama+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Iconic. Go for the morning bun and a cortado.",
  },
  {
    name: "Réveille — North Beach",
    neighborhood: "North Beach",
    address: "105 Columbus Ave, San Francisco, CA 94133",
    category: "coffee-food" as const,
    tags: JSON.stringify(["wifi", "outlets", "food-available", "neighborhood"]),
    workRating: 4,
    coffeeRating: 5,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Reveille+Coffee+Columbus+Ave+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Prime North Beach corner with great food and coffee.",
  },
  {
    name: "Réveille — Castro",
    neighborhood: "Castro",
    address: "4076 18th St, San Francisco, CA 94114",
    category: "coffee-food" as const,
    tags: JSON.stringify(["wifi", "food-available", "neighborhood"]),
    workRating: 3,
    coffeeRating: 5,
    hours: "Daily 7am–5pm",
    mapsUrl: "https://maps.google.com/?q=Reveille+Coffee+Castro+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Sunny Castro café with great food options.",
  },
  {
    name: "Capital One Café",
    neighborhood: "Union Square",
    address: "240 Stockton St, San Francisco, CA 94108",
    category: "coworking" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "free", "roomy", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 3,
    hours: "Mon–Fri 8am–7pm, Sat–Sun 9am–6pm",
    mapsUrl: "https://maps.google.com/?q=Capital+One+Cafe+Stockton+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Underrated work spot. Free wifi, lots of outlets, low judgment.",
  },
  {
    name: "NEON",
    neighborhood: "Mission",
    address: "3154 16th St, San Francisco, CA 94103",
    category: "coworking" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "standing-desks", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 4,
    hours: "Mon–Fri 8am–6pm",
    mapsUrl: "https://maps.google.com/?q=NEON+Coworking+16th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Hybrid café-coworking. Fast wifi, standing desks available.",
  },
  {
    name: "Ecosystem Coworking SF",
    neighborhood: "SoMa",
    address: "821 Folsom St, San Francisco, CA 94107",
    category: "coworking" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "meeting-rooms", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 3,
    hours: "Mon–Fri 8am–6pm",
    mapsUrl: "https://maps.google.com/?q=Ecosystem+Coworking+Folsom+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Casual SoMa coworking with café-style seating.",
  },
  {
    name: "Corgi Café",
    neighborhood: "Financial District",
    address: "116 New Montgomery St, San Francisco, CA 94105",
    category: "coworking" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "free", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 3,
    hours: "Mon–Fri 7:30am–5pm",
    mapsUrl: "https://maps.google.com/?q=Corgi+Cafe+New+Montgomery+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "No-frills FiDi workspace. Excellent wifi, minimal distraction.",
  },
  {
    name: "The Social Study",
    neighborhood: "Hayes Valley",
    address: "601 Hayes St, San Francisco, CA 94102",
    category: "coworking" as const,
    tags: JSON.stringify(["wifi", "outlets", "laptop-friendly", "neighborhood", "founder-crowd"]),
    workRating: 5,
    coffeeRating: 4,
    hours: "Daily 8am–7pm",
    mapsUrl: "https://maps.google.com/?q=The+Social+Study+Hayes+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Beautifully designed Hayes Valley work café.",
  },
  {
    name: "Rhea's Deli & Market",
    neighborhood: "Mission",
    address: "3397 18th St, San Francisco, CA 94110",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["banh-mi", "coffee", "neighborhood", "quick"]),
    workRating: 1,
    coffeeRating: 3,
    hours: "Mon–Sat 8am–5pm",
    mapsUrl: "https://maps.google.com/?q=Rheas+Deli+18th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Legendary banh mi spot on 18th. Grab and go.",
  },
  {
    name: "Deli Board",
    neighborhood: "SoMa",
    address: "1058 Folsom St, San Francisco, CA 94103",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["build-your-own", "hearty", "lunch"]),
    workRating: 1,
    coffeeRating: 2,
    hours: "Mon–Fri 10:30am–3pm",
    mapsUrl: "https://maps.google.com/?q=Deli+Board+Folsom+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "SoMa institution. The #14 is legendary.",
  },
  {
    name: "Lucinda's Deli & More",
    neighborhood: "NoPa",
    address: "800 Divisadero St, San Francisco, CA 94117",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["neighborhood", "quick", "affordable"]),
    workRating: 1,
    coffeeRating: 2,
    hours: "Mon–Sat 9am–5pm",
    mapsUrl: "https://maps.google.com/?q=Lucindas+Deli+Divisadero+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "NoPa neighborhood staple with excellent sandwiches.",
  },
  {
    name: "Giordano Bros.",
    neighborhood: "Mission",
    address: "3108 16th St, San Francisco, CA 94103",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["pittsburgh-style", "hearty", "lunch"]),
    workRating: 1,
    coffeeRating: 2,
    hours: "Daily 11am–10pm",
    mapsUrl: "https://maps.google.com/?q=Giordano+Bros+16th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Pittsburgh-style sandwiches (fries on top). Unconventional but excellent.",
  },
  {
    name: "Ike's Love & Sandwiches",
    neighborhood: "Multiple",
    address: "3489 16th St, San Francisco, CA 94114",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["build-your-own", "hearty", "vegetarian-options"]),
    workRating: 1,
    coffeeRating: 1,
    hours: "Daily 10am–9pm",
    mapsUrl: "https://maps.google.com/?q=Ikes+Sandwiches+16th+St+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "SF chain with hundreds of creative sandwiches. Order ahead.",
  },
  {
    name: "Blue Fog Market",
    neighborhood: "Pacific Heights",
    address: "2435 Polk St, San Francisco, CA 94109",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["neighborhood", "deli", "affordable"]),
    workRating: 1,
    coffeeRating: 2,
    hours: "Daily 8am–8pm",
    mapsUrl: "https://maps.google.com/?q=Blue+Fog+Market+Polk+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Friendly corner market deli on Polk. Good sandwiches at great prices.",
  },
  {
    name: "Molinari Delicatessen",
    neighborhood: "North Beach",
    address: "373 Columbus Ave, San Francisco, CA 94133",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["italian", "traditional", "neighborhood"]),
    workRating: 1,
    coffeeRating: 1,
    hours: "Mon–Fri 8am–5:30pm, Sat 7:30am–5:30pm",
    mapsUrl: "https://maps.google.com/?q=Molinari+Delicatessen+Columbus+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "SF institution since 1896. The Italian sub is a must.",
  },
  {
    name: "Palm City",
    neighborhood: "Outer Sunset",
    address: "4141 Judah St, San Francisco, CA 94122",
    category: "sandwich-lunch" as const,
    tags: JSON.stringify(["neighborhood", "quick", "affordable"]),
    workRating: 1,
    coffeeRating: 2,
    hours: "Daily 10am–8pm",
    mapsUrl: "https://maps.google.com/?q=Palm+City+Judah+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Outer Sunset neighborhood gem for a quick midday bite.",
  },
  {
    name: "Dandelion Chocolate Café",
    neighborhood: "Mission",
    address: "740 Valencia St, San Francisco, CA 94110",
    category: "coffee-food" as const,
    tags: JSON.stringify(["chocolate", "interesting-beans", "food-available", "cozy", "neighborhood"]),
    workRating: 3,
    coffeeRating: 4,
    hours: "Daily 9am–9pm",
    mapsUrl: "https://maps.google.com/?q=Dandelion+Chocolate+Valencia+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Bean-to-bar chocolate factory with a beautiful café. Order the drinking chocolate.",
  },
  {
    name: "Devout Coffee",
    neighborhood: "Excelsior",
    address: "4411 Mission St, San Francisco, CA 94112",
    category: "coffee-only" as const,
    tags: JSON.stringify(["pour-over", "interesting-beans", "neighborhood", "quiet"]),
    workRating: 3,
    coffeeRating: 5,
    hours: "Mon–Sat 7am–4pm, Sun 8am–3pm",
    mapsUrl: "https://maps.google.com/?q=Devout+Coffee+Mission+St+Excelsior+SF",
    status: "active" as const,
    dateAdded: "2024-01-01",
    notes: "Outer Mission gem with serious single-origin sourcing. Worth the trip.",
  },
];

export async function seedIfEmpty(): Promise<void> {
  try {
    const result = await db.select({ value: count() }).from(venuesTable);
    const venueCount = Number(result[0]?.value ?? 0);

    if (venueCount > 0) {
      logger.info({ venueCount }, "Database already seeded, skipping");
      return;
    }

    logger.info("Venues table empty — seeding initial data");
    for (const venue of VENUES) {
      await db.insert(venuesTable).values(venue);
    }
    logger.info({ count: VENUES.length }, "Initial seed complete");
  } catch (err) {
    logger.error({ err }, "Auto-seed failed");
  }
}
